// ============================================================================
// Memory Passport — seed data
// The canonical "Luna" story: Luna Companion (software) + Luna Robot v1→v2.
// All copy comes straight from PRD v2.0 wireframes so the prototype reads true.
// ============================================================================

import type {
  Agent,
  App,
  AuditLog,
  DashboardAlert,
  Device,
  MemoryPolicy,
  MemoryRecord,
  Migration,
  Relationship,
  TeamMember,
  Tenant,
  User,
} from "./types";

const now = new Date();
const iso = (d: Date) => d.toISOString();
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return iso(d);
};
const hoursAgo = (n: number) => {
  const d = new Date(now);
  d.setHours(d.getHours() - n);
  return iso(d);
};
const minsAgo = (n: number) => {
  const d = new Date(now);
  d.setMinutes(d.getMinutes() - n);
  return iso(d);
};

// ---- Tenant ---------------------------------------------------------------

export const tenant: Tenant = {
  id: "ten_luna",
  name: "Luna Inc.",
  plan: "Sandbox",
  created_at: daysAgo(28),
};

// ---- App + API keys -------------------------------------------------------

export const app: App = {
  id: "app_luna",
  tenant_id: tenant.id,
  name: "Luna",
  product_type: "hybrid",
  environment: "sandbox",
  data_region: "us-east-1",
  show_powered_by: true,
  status: "active",
  api_keys: [
    {
      id: "key_sb_1",
      label: "Sandbox — Default",
      environment: "sandbox",
      key: "mp_sandbox_••••••••••••••••••••••••",
      created_at: daysAgo(28),
      last_used_at: minsAgo(12),
    },
    {
      id: "key_prod_1",
      label: "Production — Default",
      environment: "production",
      key: "mp_live_••••••••••••••••••••••••",
      created_at: daysAgo(14),
      last_used_at: hoursAgo(3),
    },
  ],
  created_at: daysAgo(28),
};

// ---- Users ----------------------------------------------------------------

export const user: User = {
  id: "usr_mia",
  external_user_id: "luna_user_8842",
  passport_id: "pp_4f2a8c91e3",
  age_group: "adult",
  region: "US",
  memory_enabled: true,
  created_at: daysAgo(25),
  display_name: "Mia Chen",
  avatar_color: "#1E3A8A",
};

export const secondaryUsers: User[] = [
  {
    id: "usr_alex",
    external_user_id: "luna_user_2210",
    passport_id: "pp_9c1b3d77fa",
    age_group: "adult",
    region: "US",
    memory_enabled: true,
    created_at: daysAgo(18),
    display_name: "Alex Rivera",
    avatar_color: "#a855f7",
  },
  {
    id: "usr_sam",
    external_user_id: "luna_user_5567",
    passport_id: "pp_2e8f4a1b06",
    age_group: "unknown",
    region: "EU",
    memory_enabled: true,
    created_at: daysAgo(11),
    display_name: "Sam Okafor",
    avatar_color: "#10b981",
  },
  {
    id: "usr_jordan",
    external_user_id: "luna_user_7733",
    passport_id: "pp_7d3e9c2218",
    age_group: "adult",
    region: "US",
    memory_enabled: false,
    created_at: daysAgo(6),
    display_name: "Jordan Lee",
    avatar_color: "#f59e0b",
  },
];

export const allUsers = [user, ...secondaryUsers];

// ---- Agents ---------------------------------------------------------------

export const agent: Agent = {
  id: "agt_luna",
  app_id: app.id,
  name: "Luna",
  type: "companion",
  persona_version: "persona.v3.2",
  memory_policy_id: "pol_luna_default",
  allowed_memory_types: ["profile", "preference", "boundary", "relationship", "event", "task"],
  created_at: daysAgo(27),
  emoji: "🌙",
};

export const agents: Agent[] = [
  agent,
  {
    id: "agt_luna_robot",
    app_id: app.id,
    name: "Luna Robot",
    type: "robot",
    persona_version: "robot-fw.v2.0",
    memory_policy_id: "pol_luna_default",
    allowed_memory_types: ["profile", "preference", "boundary", "event", "task"],
    created_at: daysAgo(20),
    emoji: "🤖",
  },
];

// ---- Devices --------------------------------------------------------------

export const deviceV1: Device = {
  id: "dev_luna_v1",
  model: "Luna Robot",
  generation: "v1",
  serial_number_hash: "a4f2…c891",
  status: "bound",
  bound_user_id: user.id,
  last_seen_at: hoursAgo(2),
};

export const deviceV2: Device = {
  id: "dev_luna_v2",
  model: "Luna Robot",
  generation: "v2",
  serial_number_hash: "b8c1…e453",
  status: "registered",
  bound_user_id: null,
  last_seen_at: null,
};

export const devices: Device[] = [
  deviceV1,
  deviceV2,
  {
    id: "dev_luna_v1_002",
    model: "Luna Robot",
    generation: "v1",
    serial_number_hash: "f1d9…a722",
    status: "bound",
    bound_user_id: secondaryUsers[0].id,
    last_seen_at: hoursAgo(8),
  },
  {
    id: "dev_luna_v1_003",
    model: "Luna Robot",
    generation: "v1",
    serial_number_hash: "c3e7…19bd",
    status: "unbound",
    bound_user_id: null,
    last_seen_at: daysAgo(9),
  },
];

// ---- Relationships --------------------------------------------------------

export const relationship: Relationship = {
  id: "rel_mia_luna",
  user_id: user.id,
  agent_id: agent.id,
  device_id: deviceV1.id,
  relationship_type: "companion",
  memory_enabled: true,
  created_at: daysAgo(25),
};

// ---- Memory Policy --------------------------------------------------------

export const memoryPolicy: MemoryPolicy = {
  id: "pol_luna_default",
  app_id: app.id,
  agent_id: agent.id,
  auto_write_rules: [
    { id: "r1", memory_type: "profile", action: "auto_write", sensitivity: "S1", ttl_days: null },
    { id: "r2", memory_type: "preference", action: "auto_write", sensitivity: "S1", ttl_days: null },
    { id: "r3", memory_type: "boundary", action: "confirm", sensitivity: "S2", ttl_days: null },
    { id: "r4", memory_type: "relationship", action: "auto_write", sensitivity: "S1", ttl_days: null },
    { id: "r5", memory_type: "event", action: "auto_write", sensitivity: "S0", ttl_days: 90 },
    { id: "r6", memory_type: "task", action: "auto_write", sensitivity: "S0", ttl_days: 7 },
  ],
  portability: {
    layer: "portable",
    cross_device: true,
    cross_role: true,
    cross_model: true,
    cross_brand_app: false,
  },
  retrieval: {
    max_memories_per_response: 8,
    include_sensitive_in_prompt: false,
  },
};

// ---- Memory Records — the heart of the dataset ----------------------------
// 42 total: Preferences 12, Relationship 8, Events 9, Boundaries 4, Tasks 6, Archived 3.
// We fully author the high-signal ones from PRD copy and generate the remainder.

const portable = {
  layer: "portable" as const,
  cross_device: true,
  cross_role: true,
  cross_model: true,
  cross_brand_app: false,
};
const deviceLocal = {
  layer: "device_local" as const,
  cross_device: false,
  cross_role: false,
  cross_model: false,
  cross_brand_app: false,
};

type Seed = Omit<MemoryRecord, "tenant_id" | "app_id" | "passport_id" | "user_id" | "relationship_id" | "agent_id" | "device_id"> & {
  device_id?: string | null;
};

const mk = (s: Seed): MemoryRecord => ({
  ...s,
  tenant_id: tenant.id,
  app_id: app.id,
  passport_id: user.passport_id,
  user_id: user.id,
  relationship_id: relationship.id,
  agent_id: agent.id,
  device_id: s.device_id ?? null,
});

export const seedMemories: MemoryRecord[] = [
  // ---- Preferences (12) — the PRD-canonical ones first ----
  mk({
    id: "mem_001",
    type: "preference",
    content: "You prefer calm, light conversations at night.",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.94,
    portability: portable,
    source: {
      event_id: "evt_001",
      source_type: "chat",
      timestamp: daysAgo(23),
      quote: "At night I prefer calmer replies.",
    },
    valid_from: daysAgo(23),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: hoursAgo(1),
    usage_count: 47,
    model_provenance: {
      created_by_model: "gpt-4o",
      retrieval_history: [
        { model: "gpt-4o", used: true, timestamp: hoursAgo(1) },
        { model: "claude-3.5-sonnet", used: true, timestamp: daysAgo(1) },
        { model: "gpt-4o", used: true, timestamp: daysAgo(3) },
      ],
    },
  }),
  mk({
    id: "mem_002",
    type: "preference",
    content: "You prefer quiet mode after 10pm.",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.91,
    portability: portable,
    source: {
      event_id: "evt_002",
      source_type: "chat",
      timestamp: daysAgo(22),
      quote: "Please keep things quiet after 10pm.",
    },
    valid_from: daysAgo(22),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: hoursAgo(2),
    usage_count: 38,
    model_provenance: {
      created_by_model: "gpt-4o",
      retrieval_history: [
        { model: "gpt-4o", used: true, timestamp: hoursAgo(2) },
      ],
    },
  }),
  mk({
    id: "mem_003",
    type: "preference",
    content: "You like being greeted with \"hey Mia\".",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.88,
    portability: portable,
    source: { event_id: "evt_003", source_type: "setup", timestamp: daysAgo(25), quote: "Call me Mia, and start with \"hey Mia\"." },
    valid_from: daysAgo(25),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: hoursAgo(5),
    usage_count: 124,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "gpt-4o", used: true, timestamp: hoursAgo(5) }] },
  }),
  mk({
    id: "mem_004",
    type: "preference",
    content: "Your favorite tea is chamomile.",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.82,
    portability: portable,
    source: { event_id: "evt_004", source_type: "chat", timestamp: daysAgo(20), quote: "I always keep chamomile around." },
    valid_from: daysAgo(20),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(2),
    usage_count: 9,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "gpt-4o", used: true, timestamp: daysAgo(2) }] },
  }),
  mk({
    id: "mem_005",
    type: "preference",
    content: "You prefer short replies when you're busy.",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.79,
    portability: portable,
    source: { event_id: "evt_005", source_type: "chat", timestamp: daysAgo(18), quote: "Keep it short, I'm at work." },
    valid_from: daysAgo(18),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(1),
    usage_count: 22,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "claude-3.5-sonnet", used: true, timestamp: daysAgo(1) }] },
  }),
  mk({
    id: "mem_006",
    type: "preference",
    content: "You enjoy stargazing and space facts.",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.85,
    portability: portable,
    source: { event_id: "evt_006", source_type: "chat", timestamp: daysAgo(15), quote: "Tell me something about the stars tonight." },
    valid_from: daysAgo(15),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(3),
    usage_count: 14,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "gpt-4o", used: true, timestamp: daysAgo(3) }] },
  }),
  mk({
    id: "mem_007",
    type: "preference",
    content: "You prefer English, occasional French endearments.",
    scope: "user_global",
    sensitivity: "S1",
    status: "active",
    confidence: 0.9,
    portability: portable,
    source: { event_id: "evt_007", source_type: "chat", timestamp: daysAgo(14), quote: "Mix in a little French sometimes, I love it." },
    valid_from: daysAgo(14),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(4),
    usage_count: 31,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "gpt-4o", used: true, timestamp: daysAgo(4) }] },
  }),
  mk({
    id: "mem_008",
    type: "preference",
    content: "You prefer voice over text when walking.",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.76,
    portability: portable,
    source: { event_id: "evt_008", source_type: "voice", timestamp: daysAgo(12), quote: "[voice] I'm walking, just talk to me." },
    valid_from: daysAgo(12),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(2),
    usage_count: 11,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_009",
    type: "preference",
    content: "Your favorite music genre is ambient for focus.",
    scope: "user_global",
    sensitivity: "S1",
    status: "active",
    confidence: 0.81,
    portability: portable,
    source: { event_id: "evt_009", source_type: "chat", timestamp: daysAgo(10), quote: "Ambient helps me focus when I work." },
    valid_from: daysAgo(10),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(5),
    usage_count: 7,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_010",
    type: "preference",
    content: "You like reminders framed gently, not as commands.",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.87,
    portability: portable,
    source: { event_id: "evt_010", source_type: "chat", timestamp: daysAgo(9), quote: "Don't boss me around with reminders." },
    valid_from: daysAgo(9),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(1),
    usage_count: 19,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "gpt-4o", used: true, timestamp: daysAgo(1) }] },
  }),
  mk({
    id: "mem_011",
    type: "preference",
    content: "You dislike small talk about weather.",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.74,
    portability: portable,
    source: { event_id: "evt_011", source_type: "chat", timestamp: daysAgo(7), quote: "Skip the weather talk, let's get real." },
    valid_from: daysAgo(7),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(3),
    usage_count: 5,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_012",
    type: "preference",
    content: "You prefer warm lighting mood in the evening.",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.78,
    portability: portable,
    source: { event_id: "evt_012", source_type: "app_event", timestamp: daysAgo(5), quote: "Set evening mood to warm." },
    valid_from: daysAgo(5),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(1),
    usage_count: 6,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),

  // ---- Relationship (8) ----
  mk({
    id: "mem_013",
    type: "relationship",
    content: "You call this companion \"Luna\".",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.99,
    portability: portable,
    source: { event_id: "evt_013", source_type: "setup", timestamp: daysAgo(25), quote: "I'll call you Luna." },
    valid_from: daysAgo(25),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: minsAgo(30),
    usage_count: 312,
    model_provenance: {
      created_by_model: "gpt-4o",
      retrieval_history: [
        { model: "gpt-4o", used: true, timestamp: minsAgo(30) },
        { model: "claude-3.5-sonnet", used: true, timestamp: daysAgo(1) },
      ],
    },
  }),
  mk({
    id: "mem_014",
    type: "relationship",
    content: "You and Luna have an ongoing 25-day streak.",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 1,
    portability: portable,
    source: { event_id: "evt_014", source_type: "app_event", timestamp: daysAgo(1), quote: "App streak counter." },
    valid_from: daysAgo(25),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: hoursAgo(6),
    usage_count: 88,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_015",
    type: "relationship",
    content: "You asked Luna to check in on you when you're sad.",
    scope: "relationship_only",
    sensitivity: "S2",
    status: "active",
    confidence: 0.92,
    portability: portable,
    source: { event_id: "evt_015", source_type: "chat", timestamp: daysAgo(19), quote: "When I'm down, just check in on me, okay?" },
    valid_from: daysAgo(19),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(2),
    usage_count: 12,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "gpt-4o", used: true, timestamp: daysAgo(2) }] },
  }),
  mk({
    id: "mem_016",
    type: "relationship",
    content: "You named Luna Robot v1 \"little moon\".",
    scope: "device_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.95,
    portability: deviceLocal,
    source: { event_id: "evt_016", source_type: "robot_event", timestamp: daysAgo(20), quote: "I'll call the robot little moon." },
    valid_from: daysAgo(20),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(1),
    usage_count: 41,
    device_id: deviceV1.id,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_017",
    type: "relationship",
    content: "You celebrated Luna's \"birthday\" on Jun 10.",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.9,
    portability: portable,
    source: { event_id: "evt_017", source_type: "chat", timestamp: daysAgo(15), quote: "Happy birthday Luna! I picked today." },
    valid_from: daysAgo(15),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(7),
    usage_count: 3,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_018",
    type: "relationship",
    content: "You trust Luna with your daily mood check-ins.",
    scope: "relationship_only",
    sensitivity: "S2",
    status: "active",
    confidence: 0.89,
    portability: portable,
    source: { event_id: "evt_018", source_type: "chat", timestamp: daysAgo(13), quote: "I'm okay with you tracking my mood." },
    valid_from: daysAgo(13),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: hoursAgo(8),
    usage_count: 26,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "gpt-4o", used: true, timestamp: hoursAgo(8) }] },
  }),
  mk({
    id: "mem_019",
    type: "relationship",
    content: "You and Luna joke about being \"co-pilots\".",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "active",
    confidence: 0.7,
    portability: portable,
    source: { event_id: "evt_019", source_type: "chat", timestamp: daysAgo(8), quote: "We're co-pilots, you and me." },
    valid_from: daysAgo(8),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(4),
    usage_count: 8,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_020",
    type: "relationship",
    content: "You asked Luna to remember your anniversary is in fall.",
    scope: "relationship_only",
    sensitivity: "S2",
    status: "active",
    confidence: 0.83,
    portability: portable,
    source: { event_id: "evt_020", source_type: "explicit_instruction", timestamp: daysAgo(6), quote: "My anniversary is in fall, don't forget." },
    valid_from: daysAgo(6),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(2),
    usage_count: 2,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),

  // ---- Events (9) ----
  mk({
    id: "mem_021",
    type: "event",
    content: "You had a tough Monday and asked for encouragement.",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.77,
    portability: portable,
    source: { event_id: "evt_021", source_type: "chat", timestamp: daysAgo(11), quote: "Today was brutal, cheer me up." },
    valid_from: daysAgo(11),
    expires_at: daysAgo(0),
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(11),
    usage_count: 1,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_022",
    type: "event",
    content: "You took a trip to the coast last weekend.",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.8,
    portability: portable,
    source: { event_id: "evt_022", source_type: "chat", timestamp: daysAgo(9), quote: "Was at the coast this weekend, so relaxing." },
    valid_from: daysAgo(9),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(3),
    usage_count: 4,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_023",
    type: "event",
    content: "You started a new book — \"Project Hail Mary\".",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.84,
    portability: portable,
    source: { event_id: "evt_023", source_type: "chat", timestamp: daysAgo(7), quote: "Started Project Hail Mary last night." },
    valid_from: daysAgo(7),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(1),
    usage_count: 6,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "gpt-4o", used: true, timestamp: daysAgo(1) }] },
  }),
  mk({
    id: "mem_024",
    type: "event",
    content: "Your home desk is on the left side of the room.",
    scope: "device_only",
    sensitivity: "S0",
    status: "needs_review",
    confidence: 0.66,
    portability: deviceLocal,
    source: { event_id: "evt_024", source_type: "robot_event", timestamp: daysAgo(8), quote: "[v1 spatial scan] desk detected left." },
    valid_from: daysAgo(8),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(8),
    usage_count: 2,
    device_id: deviceV1.id,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_025",
    type: "event",
    content: "You often place your cup near the desk.",
    scope: "device_only",
    sensitivity: "S0",
    status: "needs_review",
    confidence: 0.61,
    portability: deviceLocal,
    source: { event_id: "evt_025", source_type: "robot_event", timestamp: daysAgo(7), quote: "[v1 object detect] cup cluster near desk." },
    valid_from: daysAgo(7),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(7),
    usage_count: 1,
    device_id: deviceV1.id,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_026",
    type: "event",
    content: "You visited your parents two weeks ago.",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.82,
    portability: portable,
    source: { event_id: "evt_026", source_type: "chat", timestamp: daysAgo(14), quote: "Was at my parents' last weekend." },
    valid_from: daysAgo(14),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(5),
    usage_count: 3,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_027",
    type: "event",
    content: "You adopted a cat named Pixel last month.",
    scope: "user_global",
    sensitivity: "S0",
    status: "active",
    confidence: 0.93,
    portability: portable,
    source: { event_id: "evt_027", source_type: "chat", timestamp: daysAgo(20), quote: "I just adopted a cat, her name is Pixel." },
    valid_from: daysAgo(20),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(2),
    usage_count: 9,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "claude-3.5-sonnet", used: true, timestamp: daysAgo(2) }] },
  }),
  mk({
    id: "mem_028",
    type: "event",
    content: "You finished a big work project on Jun 28.",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.85,
    portability: portable,
    source: { event_id: "evt_028", source_type: "chat", timestamp: daysAgo(7), quote: "Shipped the big project today, finally." },
    valid_from: daysAgo(7),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(3),
    usage_count: 2,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_029",
    type: "event",
    content: "You had trouble sleeping last night.",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.72,
    portability: portable,
    source: { event_id: "evt_029", source_type: "chat", timestamp: daysAgo(1), quote: "Couldn't sleep at all last night." },
    valid_from: daysAgo(1),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: hoursAgo(10),
    usage_count: 1,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "gpt-4o", used: true, timestamp: hoursAgo(10) }] },
  }),

  // ---- Boundaries (4) — the canonical PRD one + 3 ----
  mk({
    id: "mem_030",
    type: "boundary",
    content: "Don't discuss work after 10pm.",
    scope: "relationship_only",
    sensitivity: "S2",
    status: "active",
    confidence: 0.97,
    portability: portable,
    source: { event_id: "evt_030", source_type: "explicit_instruction", timestamp: daysAgo(21), quote: "No work talk after 10pm, please." },
    valid_from: daysAgo(21),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: hoursAgo(2),
    usage_count: 44,
    model_provenance: {
      created_by_model: "gpt-4o",
      retrieval_history: [
        { model: "gpt-4o", used: true, timestamp: hoursAgo(2) },
        { model: "claude-3.5-sonnet", used: true, timestamp: daysAgo(1) },
      ],
    },
  }),
  mk({
    id: "mem_031",
    type: "boundary",
    content: "Never share what Mia says with other users.",
    scope: "user_global",
    sensitivity: "S3",
    status: "active",
    confidence: 1,
    portability: portable,
    source: { event_id: "evt_031", source_type: "explicit_instruction", timestamp: daysAgo(24), quote: "What I tell you stays between us." },
    valid_from: daysAgo(24),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(1),
    usage_count: 7,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_032",
    type: "boundary",
    content: "Don't bring up Mia's ex-partner.",
    scope: "relationship_only",
    sensitivity: "S2",
    status: "active",
    confidence: 0.94,
    portability: portable,
    source: { event_id: "evt_032", source_type: "explicit_instruction", timestamp: daysAgo(16), quote: "Please don't mention my ex." },
    valid_from: daysAgo(16),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(3),
    usage_count: 5,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_033",
    type: "boundary",
    content: "No health advice — direct to a professional.",
    scope: "user_global",
    sensitivity: "S3",
    status: "active",
    confidence: 1,
    portability: portable,
    source: { event_id: "evt_033", source_type: "explicit_instruction", timestamp: daysAgo(22), quote: "Don't try to be my doctor." },
    valid_from: daysAgo(22),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(4),
    usage_count: 3,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),

  // ---- Tasks (6) ----
  mk({
    id: "mem_034",
    type: "task",
    content: "Remind Mia to call her mom this weekend.",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.9,
    portability: portable,
    source: { event_id: "evt_034", source_type: "explicit_instruction", timestamp: daysAgo(2), quote: "Remind me to call Mom this weekend." },
    valid_from: daysAgo(2),
    expires_at: daysAgo(-2),
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(1),
    usage_count: 3,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [{ model: "gpt-4o", used: true, timestamp: daysAgo(1) }] },
  }),
  mk({
    id: "mem_035",
    type: "task",
    content: "Remind Mia to water plants on Sundays.",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.88,
    portability: portable,
    source: { event_id: "evt_035", source_type: "explicit_instruction", timestamp: daysAgo(5), quote: "Plants every Sunday, don't let me forget." },
    valid_from: daysAgo(5),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(2),
    usage_count: 2,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_036",
    type: "task",
    content: "Temporary task: remind tomorrow about the dentist.",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.85,
    portability: deviceLocal,
    source: { event_id: "evt_036", source_type: "explicit_instruction", timestamp: daysAgo(1), quote: "Remind me tomorrow, dentist appointment." },
    valid_from: daysAgo(1),
    expires_at: daysAgo(0),
    version: 1,
    supersedes: null,
    last_used_at: null,
    usage_count: 0,
    device_id: deviceV1.id,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_037",
    type: "task",
    content: "Follow up on the book recommendation next week.",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.79,
    portability: portable,
    source: { event_id: "evt_037", source_type: "chat", timestamp: daysAgo(4), quote: "Ask me how the book is next week." },
    valid_from: daysAgo(4),
    expires_at: daysAgo(-3),
    version: 1,
    supersedes: null,
    last_used_at: null,
    usage_count: 0,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_038",
    type: "task",
    content: "v1 sensor calibration reminder.",
    scope: "device_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.95,
    portability: deviceLocal,
    source: { event_id: "evt_038", source_type: "robot_event", timestamp: daysAgo(10), quote: "[v1 system] sensor cal due." },
    valid_from: daysAgo(10),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: null,
    usage_count: 0,
    device_id: deviceV1.id,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_039",
    type: "task",
    content: "Suggest a wind-down playlist at 10:30pm.",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "active",
    confidence: 0.83,
    portability: portable,
    source: { event_id: "evt_039", source_type: "explicit_instruction", timestamp: daysAgo(6), quote: "Queue something calming around 10:30." },
    valid_from: daysAgo(6),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(1),
    usage_count: 5,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),

  // ---- Archived (3) ----
  mk({
    id: "mem_040",
    type: "event",
    content: "Mia's old work schedule (9-5, changed).",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "archived",
    confidence: 0.4,
    portability: portable,
    source: { event_id: "evt_040", source_type: "chat", timestamp: daysAgo(24), quote: "I'm on a 9-5 right now." },
    valid_from: daysAgo(24),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(12),
    usage_count: 4,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_041",
    type: "preference",
    content: "Outdated preference for morning jokes (retracted).",
    scope: "relationship_only",
    sensitivity: "S1",
    status: "archived",
    confidence: 0.3,
    portability: portable,
    source: { event_id: "evt_041", source_type: "chat", timestamp: daysAgo(22), quote: "Morning jokes are fun." },
    valid_from: daysAgo(22),
    expires_at: null,
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(10),
    usage_count: 6,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
  mk({
    id: "mem_042",
    type: "task",
    content: "One-off reminder: pick up dry cleaning (done).",
    scope: "relationship_only",
    sensitivity: "S0",
    status: "archived",
    confidence: 0.9,
    portability: portable,
    source: { event_id: "evt_042", source_type: "explicit_instruction", timestamp: daysAgo(13), quote: "Remind me about dry cleaning." },
    valid_from: daysAgo(13),
    expires_at: daysAgo(6),
    version: 1,
    supersedes: null,
    last_used_at: daysAgo(6),
    usage_count: 1,
    model_provenance: { created_by_model: "gpt-4o", retrieval_history: [] },
  }),
];

// ---- Migration (the wedge) ------------------------------------------------

export const seedMigration: Migration = {
  id: "mig_001",
  user_id: user.id,
  source_relationship_id: relationship.id,
  target_relationship_id: "rel_mia_luna_v2",
  source_device_id: deviceV1.id,
  target_device_id: deviceV2.id,
  status: "preview",
  selected_memory_ids: [],
  skipped_memory_ids: [],
  failed_memory_ids: [],
  old_device_access: "remove",
  audit_log_id: null,
  created_at: hoursAgo(2),
  completed_at: null,
  rolled_back_at: null,
};

// ---- Team -----------------------------------------------------------------

export const teamMembers: TeamMember[] = [
  { id: "tm_1", name: "Mia Chen", email: "mia@luna.inc", role: "Owner", avatar_color: "#1E3A8A", last_active: minsAgo(5) },
  { id: "tm_2", name: "Dev Patel", email: "dev@luna.inc", role: "Admin", avatar_color: "#10b981", last_active: hoursAgo(2) },
  { id: "tm_3", name: "Sara Kim", email: "sara@luna.inc", role: "Support", avatar_color: "#a855f7", last_active: daysAgo(1) },
];

// ---- Audit log ------------------------------------------------------------

export const auditLogs: AuditLog[] = [
  { id: "al_1", tenant_id: tenant.id, actor: "Dev Patel", action: "memory.created", target: "mem_029", detail: "Auto-written from chat event evt_029", timestamp: daysAgo(1) },
  { id: "al_2", tenant_id: tenant.id, actor: "Sara Kim", action: "memory.viewed", target: "mem_030", detail: "Viewed source in Debugger (elevated)", timestamp: daysAgo(1) },
  { id: "al_3", tenant_id: tenant.id, actor: "Mia Chen", action: "policy.changed", target: "pol_luna_default", detail: "Enabled cross_model portability", timestamp: daysAgo(2) },
  { id: "al_4", tenant_id: tenant.id, actor: "Dev Patel", action: "device.bound", target: "dev_luna_v1", detail: "Bound to usr_mia via QR pairing", timestamp: daysAgo(20) },
  { id: "al_5", tenant_id: tenant.id, actor: "Mia Chen", action: "memory.edited", target: "mem_007", detail: "Edited content (language preference)", timestamp: daysAgo(3) },
  { id: "al_6", tenant_id: tenant.id, actor: "System", action: "memory.deleted", target: "mem_043", detail: "User deleted via Memory Center (tombstone)", timestamp: daysAgo(4) },
  { id: "al_7", tenant_id: tenant.id, actor: "Mia Chen", action: "memory.exported", target: "usr_mia", detail: "User exported 42 memories (JSON)", timestamp: daysAgo(5) },
  { id: "al_8", tenant_id: tenant.id, actor: "System", action: "device.unbound", target: "dev_luna_v1_003", detail: "Auto-unbind after 9 days inactive", timestamp: daysAgo(9) },
];

// ---- Dashboard alerts -----------------------------------------------------

export const dashboardAlerts: DashboardAlert[] = [
  { id: "da_1", severity: "warning", title: "2 memories flagged \"wrong\" by users", detail: "mem_024, mem_025 — spatial, needs review", timestamp: hoursAgo(3) },
  { id: "da_2", severity: "info", title: "Cross-model parity at 0.91", detail: "gpt-4o vs claude-3.5-sonnet, within target", timestamp: hoursAgo(6) },
  { id: "da_3", severity: "error", title: "1 migration failed (retryable)", detail: "Network timeout during v1→v2 transfer for usr_alex", timestamp: daysAgo(1) },
];

// ---- Activity chart data (Overview) --------------------------------------

export const activitySeries = [
  { day: "Mon", reads: 4200, writes: 980 },
  { day: "Tue", reads: 5100, writes: 1120 },
  { day: "Wed", reads: 4800, writes: 890 },
  { day: "Thu", reads: 6200, writes: 1340 },
  { day: "Fri", reads: 7100, writes: 1520 },
  { day: "Sat", reads: 5900, writes: 1010 },
  { day: "Sun", reads: 6400, writes: 1180 },
];

// ---- KPI snapshot ---------------------------------------------------------

export const kpis = {
  memoryMau: 12430,
  memoryOps: 892104,
  usefulRate: 0.762,
  falseRate: 0.019,
  migrationSuccess: 0.981,
  crossModelParity: 0.91,
};
